// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `musicRequest.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package musicRequest;

public interface _requestServerOperations
{
    String findByName(String nom, Ice.Current __current);

    String findById(int id, Ice.Current __current);

    String[] findAll(Ice.Current __current);
}
