// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `musicRequest.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package musicRequest;

public final class listsonHolder extends Ice.Holder<String[]>
{
    public
    listsonHolder()
    {
    }

    public
    listsonHolder(String[] value)
    {
        super(value);
    }
}
