// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `musicRequest.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package musicRequest;

public interface requestServer extends Ice.Object,
                                       _requestServerOperations, _requestServerOperationsNC
{
    public static final String ice_staticId = "::musicRequest::requestServer";

    public static final long serialVersionUID = -1149853895L;
}
