// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `musicRequest.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package musicRequest;

public interface requestServerPrx extends Ice.ObjectPrx
{
    public String findByName(String nom);

    public String findByName(String nom, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_findByName(String nom);

    public Ice.AsyncResult begin_findByName(String nom, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_findByName(String nom, Ice.Callback __cb);

    public Ice.AsyncResult begin_findByName(String nom, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_findByName(String nom, Callback_requestServer_findByName __cb);

    public Ice.AsyncResult begin_findByName(String nom, java.util.Map<String, String> __ctx, Callback_requestServer_findByName __cb);

    public Ice.AsyncResult begin_findByName(String nom, 
                                            IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_findByName(String nom, 
                                            IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                            IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_findByName(String nom, 
                                            java.util.Map<String, String> __ctx, 
                                            IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_findByName(String nom, 
                                            java.util.Map<String, String> __ctx, 
                                            IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                            IceInternal.Functional_BoolCallback __sentCb);

    public String end_findByName(Ice.AsyncResult __result);

    public String findById(int id);

    public String findById(int id, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_findById(int id);

    public Ice.AsyncResult begin_findById(int id, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_findById(int id, Ice.Callback __cb);

    public Ice.AsyncResult begin_findById(int id, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_findById(int id, Callback_requestServer_findById __cb);

    public Ice.AsyncResult begin_findById(int id, java.util.Map<String, String> __ctx, Callback_requestServer_findById __cb);

    public Ice.AsyncResult begin_findById(int id, 
                                          IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_findById(int id, 
                                          IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_findById(int id, 
                                          java.util.Map<String, String> __ctx, 
                                          IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_findById(int id, 
                                          java.util.Map<String, String> __ctx, 
                                          IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb);

    public String end_findById(Ice.AsyncResult __result);

    public String[] findAll();

    public String[] findAll(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_findAll();

    public Ice.AsyncResult begin_findAll(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_findAll(Ice.Callback __cb);

    public Ice.AsyncResult begin_findAll(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_findAll(Callback_requestServer_findAll __cb);

    public Ice.AsyncResult begin_findAll(java.util.Map<String, String> __ctx, Callback_requestServer_findAll __cb);

    public Ice.AsyncResult begin_findAll(IceInternal.Functional_GenericCallback1<String[]> __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_findAll(IceInternal.Functional_GenericCallback1<String[]> __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_findAll(java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_GenericCallback1<String[]> __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_findAll(java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_GenericCallback1<String[]> __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb);

    public String[] end_findAll(Ice.AsyncResult __result);
}
