// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `manageMusic.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ManageMusic;

public interface _NetworkOperations
{
    int inscription(String name, Ice.Current __current);

    void changeIp(String ip, int id, Ice.Current __current);

    void deconnexion(int id, Ice.Current __current);

    void connexion(String ip, int id, Ice.Current __current);
}
