// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `manageMusic.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ManageMusic;

public interface ManageFilePrx extends Ice.ObjectPrx
{
    public void delete(String path, int id);

    public void delete(String path, int id, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_delete(String path, int id);

    public Ice.AsyncResult begin_delete(String path, int id, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_delete(String path, int id, Ice.Callback __cb);

    public Ice.AsyncResult begin_delete(String path, int id, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_delete(String path, int id, Callback_ManageFile_delete __cb);

    public Ice.AsyncResult begin_delete(String path, int id, java.util.Map<String, String> __ctx, Callback_ManageFile_delete __cb);

    public Ice.AsyncResult begin_delete(String path, 
                                        int id, 
                                        IceInternal.Functional_VoidCallback __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_delete(String path, 
                                        int id, 
                                        IceInternal.Functional_VoidCallback __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                        IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_delete(String path, 
                                        int id, 
                                        java.util.Map<String, String> __ctx, 
                                        IceInternal.Functional_VoidCallback __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_delete(String path, 
                                        int id, 
                                        java.util.Map<String, String> __ctx, 
                                        IceInternal.Functional_VoidCallback __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                        IceInternal.Functional_BoolCallback __sentCb);

    public void end_delete(Ice.AsyncResult __result);

    public void newMusic(Sound sound, String url, int id);

    public void newMusic(Sound sound, String url, int id, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_newMusic(Sound sound, String url, int id);

    public Ice.AsyncResult begin_newMusic(Sound sound, String url, int id, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_newMusic(Sound sound, String url, int id, Ice.Callback __cb);

    public Ice.AsyncResult begin_newMusic(Sound sound, String url, int id, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_newMusic(Sound sound, String url, int id, Callback_ManageFile_newMusic __cb);

    public Ice.AsyncResult begin_newMusic(Sound sound, String url, int id, java.util.Map<String, String> __ctx, Callback_ManageFile_newMusic __cb);

    public Ice.AsyncResult begin_newMusic(Sound sound, 
                                          String url, 
                                          int id, 
                                          IceInternal.Functional_VoidCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_newMusic(Sound sound, 
                                          String url, 
                                          int id, 
                                          IceInternal.Functional_VoidCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_newMusic(Sound sound, 
                                          String url, 
                                          int id, 
                                          java.util.Map<String, String> __ctx, 
                                          IceInternal.Functional_VoidCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_newMusic(Sound sound, 
                                          String url, 
                                          int id, 
                                          java.util.Map<String, String> __ctx, 
                                          IceInternal.Functional_VoidCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb);

    public void end_newMusic(Ice.AsyncResult __result);
}
