// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `manageMusic.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ManageMusic;

public interface Request extends Ice.Object,
                                 _RequestOperations, _RequestOperationsNC
{
    public static final String ice_staticId = "::ManageMusic::Request";

    public static final long serialVersionUID = 1581578572L;
}
