// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `manageMusic.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ManageMusic;

public final class SoundsHolder extends Ice.Holder<Sound[]>
{
    public
    SoundsHolder()
    {
    }

    public
    SoundsHolder(Sound[] value)
    {
        super(value);
    }
}
